title: Weslene Uy
logo: "/images/unnamed.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of City Planning '22
  <br><br>
  University of Pennsylvania
  <br><br>
  
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/weslene-uy/">LinkedIn</a>
  </p>
   
  <p align="justify">
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
